<?php

declare(strict_types=1);

namespace App\Support;

final class InstitucionalModuleTheme
{
    /**
     * @return array{
     *     key: string,
     *     header: string,
     *     page_bg: string,
     *     kpi: string,
     *     panel: string,
     *     accent: string,
     *     accent_ring: string,
     *     accent_text: string,
     *     accent_bg: string,
     *     accent_bg_soft: string,
     *     header_from: string,
     *     header_to: string,
     *     header_via: string,
     *     header_text: string,
     *     header_subtext: string,
     *     stripe: string,
     *     pattern: string
     * }
     */
    public static function for(string $module): array
    {
        return self::MODULES[$module] ?? self::MODULES['default'];
    }

    /** @var array<string, array<string, string>> */
    private const MODULES = [
        'default' => [
            'key' => 'default',
            'header' => 'minimal',
            'page_bg' => 'bg-slate-50',
            'kpi' => 'soft',
            'panel' => 'soft',
            'accent' => 'indigo',
            'accent_ring' => 'ring-indigo-100',
            'accent_text' => 'text-indigo-700',
            'accent_bg' => 'bg-indigo-600',
            'accent_bg_soft' => 'bg-indigo-50',
            'header_from' => 'from-slate-800',
            'header_via' => 'via-slate-700',
            'header_to' => 'to-slate-900',
            'header_text' => 'text-white',
            'header_subtext' => 'text-white/80',
            'stripe' => 'border-l-indigo-500',
            'pattern' => '',
        ],
        'dashboard' => [
            'key' => 'dashboard',
            'header' => 'hero',
            'page_bg' => 'bg-gradient-to-b from-indigo-50/80 via-white to-slate-50',
            'kpi' => 'gradient',
            'panel' => 'soft',
            'accent' => 'indigo',
            'accent_ring' => 'ring-indigo-200',
            'accent_text' => 'text-indigo-700',
            'accent_bg' => 'bg-indigo-600',
            'accent_bg_soft' => 'bg-indigo-50',
            'header_from' => 'from-indigo-600',
            'header_via' => 'via-purple-600',
            'header_to' => 'to-fuchsia-500',
            'header_text' => 'text-white',
            'header_subtext' => 'text-white/85',
            'stripe' => 'border-l-indigo-500',
            'pattern' => 'inst-pattern-dots',
        ],
        'academic' => [
            'key' => 'academic',
            'header' => 'split',
            'page_bg' => 'bg-teal-50/30',
            'kpi' => 'gradient',
            'panel' => 'elevated',
            'accent' => 'violet',
            'accent_ring' => 'ring-violet-200',
            'accent_text' => 'text-violet-700',
            'accent_bg' => 'bg-violet-600',
            'accent_bg_soft' => 'bg-violet-50',
            'header_from' => 'from-teal-600',
            'header_via' => 'via-cyan-600',
            'header_to' => 'to-emerald-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-teal-100',
            'stripe' => 'border-l-teal-500',
            'pattern' => 'inst-pattern-grid',
        ],
        'ofertas' => [
            'key' => 'ofertas',
            'header' => 'stripe',
            'page_bg' => 'bg-cyan-50/30',
            'kpi' => 'pill',
            'panel' => 'sharp',
            'accent' => 'cyan',
            'accent_ring' => 'ring-cyan-200',
            'accent_text' => 'text-cyan-800',
            'accent_bg' => 'bg-cyan-600',
            'accent_bg_soft' => 'bg-cyan-50',
            'header_from' => 'from-cyan-600',
            'header_via' => 'via-teal-600',
            'header_to' => 'to-sky-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-cyan-50',
            'stripe' => 'border-l-cyan-500',
            'pattern' => 'inst-pattern-waves',
        ],
        'postulaciones' => [
            'key' => 'postulaciones',
            'header' => 'pipeline',
            'page_bg' => 'bg-blue-50/25',
            'kpi' => 'outline',
            'panel' => 'inset',
            'accent' => 'blue',
            'accent_ring' => 'ring-blue-200',
            'accent_text' => 'text-blue-700',
            'accent_bg' => 'bg-blue-600',
            'accent_bg_soft' => 'bg-blue-50',
            'header_from' => 'from-blue-600',
            'header_via' => 'via-indigo-600',
            'header_to' => 'to-blue-700',
            'header_text' => 'text-white',
            'header_subtext' => 'text-blue-100',
            'stripe' => 'border-l-blue-500',
            'pattern' => 'inst-pattern-flow',
        ],
        'evaluacion' => [
            'key' => 'evaluacion',
            'header' => 'checklist',
            'page_bg' => 'bg-amber-50/35',
            'kpi' => 'score',
            'panel' => 'ledger',
            'accent' => 'amber',
            'accent_ring' => 'ring-amber-200',
            'accent_text' => 'text-amber-800',
            'accent_bg' => 'bg-amber-500',
            'accent_bg_soft' => 'bg-amber-50',
            'header_from' => 'from-amber-500',
            'header_via' => 'via-orange-500',
            'header_to' => 'to-amber-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-amber-50',
            'stripe' => 'border-l-amber-500',
            'pattern' => 'inst-pattern-lines',
        ],
        'resultados' => [
            'key' => 'resultados',
            'header' => 'podium',
            'page_bg' => 'bg-emerald-50/30',
            'kpi' => 'medal',
            'panel' => 'dark-cap',
            'accent' => 'emerald',
            'accent_ring' => 'ring-emerald-200',
            'accent_text' => 'text-emerald-800',
            'accent_bg' => 'bg-emerald-600',
            'accent_bg_soft' => 'bg-emerald-50',
            'header_from' => 'from-emerald-600',
            'header_via' => 'via-teal-600',
            'header_to' => 'to-green-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-emerald-50',
            'stripe' => 'border-l-emerald-500',
            'pattern' => 'inst-pattern-rank',
        ],
        'asignacion' => [
            'key' => 'asignacion',
            'header' => 'action',
            'page_bg' => 'bg-orange-50/30',
            'kpi' => 'ring',
            'panel' => 'action',
            'accent' => 'orange',
            'accent_ring' => 'ring-orange-200',
            'accent_text' => 'text-orange-800',
            'accent_bg' => 'bg-orange-500',
            'accent_bg_soft' => 'bg-orange-50',
            'header_from' => 'from-orange-500',
            'header_via' => 'via-amber-500',
            'header_to' => 'to-orange-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-orange-50',
            'stripe' => 'border-l-orange-500',
            'pattern' => 'inst-pattern-bolt',
        ],
        'lista-espera' => [
            'key' => 'lista-espera',
            'header' => 'queue',
            'page_bg' => 'bg-slate-100/80',
            'kpi' => 'queue',
            'panel' => 'queue',
            'accent' => 'slate',
            'accent_ring' => 'ring-slate-300',
            'accent_text' => 'text-slate-700',
            'accent_bg' => 'bg-slate-700',
            'accent_bg_soft' => 'bg-slate-100',
            'header_from' => 'from-slate-700',
            'header_via' => 'via-slate-600',
            'header_to' => 'to-amber-700',
            'header_text' => 'text-white',
            'header_subtext' => 'text-slate-200',
            'stripe' => 'border-l-amber-500',
            'pattern' => 'inst-pattern-queue',
        ],
        'documentos' => [
            'key' => 'documentos',
            'header' => 'folder',
            'page_bg' => 'bg-rose-50/25',
            'kpi' => 'dot',
            'panel' => 'folder',
            'accent' => 'rose',
            'accent_ring' => 'ring-rose-200',
            'accent_text' => 'text-rose-800',
            'accent_bg' => 'bg-rose-600',
            'accent_bg_soft' => 'bg-rose-50',
            'header_from' => 'from-rose-600',
            'header_via' => 'via-pink-600',
            'header_to' => 'to-rose-700',
            'header_text' => 'text-white',
            'header_subtext' => 'text-rose-100',
            'stripe' => 'border-l-rose-500',
            'pattern' => 'inst-pattern-docs',
        ],
        'historial' => [
            'key' => 'historial',
            'header' => 'timeline',
            'page_bg' => 'bg-zinc-100/70',
            'kpi' => 'minimal',
            'panel' => 'timeline',
            'accent' => 'zinc',
            'accent_ring' => 'ring-zinc-300',
            'accent_text' => 'text-zinc-700',
            'accent_bg' => 'bg-zinc-800',
            'accent_bg_soft' => 'bg-zinc-100',
            'header_from' => 'from-zinc-800',
            'header_via' => 'via-zinc-700',
            'header_to' => 'to-zinc-900',
            'header_text' => 'text-white',
            'header_subtext' => 'text-zinc-300',
            'stripe' => 'border-l-zinc-600',
            'pattern' => 'inst-pattern-timeline',
        ],
        'reportes' => [
            'key' => 'reportes',
            'header' => 'analytics',
            'page_bg' => 'bg-fuchsia-50/20',
            'kpi' => 'tile',
            'panel' => 'hub',
            'accent' => 'fuchsia',
            'accent_ring' => 'ring-fuchsia-200',
            'accent_text' => 'text-fuchsia-800',
            'accent_bg' => 'bg-fuchsia-600',
            'accent_bg_soft' => 'bg-fuchsia-50',
            'header_from' => 'from-fuchsia-600',
            'header_via' => 'via-indigo-600',
            'header_to' => 'to-violet-600',
            'header_text' => 'text-white',
            'header_subtext' => 'text-fuchsia-100',
            'stripe' => 'border-l-fuchsia-500',
            'pattern' => 'inst-pattern-chart',
        ],
    ];
}
